-- Add latitude/longitude columns to amenities
ALTER TABLE "School" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "School" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "SocialLife" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "SocialLife" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Shopping" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Shopping" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "GreenSpace" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "GreenSpace" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Sport" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Sport" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Transportation" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Transportation" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Family" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Family" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Restaurant" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Restaurant" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Pet" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Pet" ADD COLUMN "longitude" DOUBLE PRECISION;

ALTER TABLE "Hobby" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Hobby" ADD COLUMN "longitude" DOUBLE PRECISION;
