-- AlterTable
ALTER TABLE "Journey" ADD COLUMN     "index" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Property" ALTER COLUMN "imageUrls" SET DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "RecommendedArea" ALTER COLUMN "placesOfInterest" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "lifestyleTags" SET DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "city" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "employment1" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "employment2" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "family" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "greenSpace" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "hobbies" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "pets" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "restaurants" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "shopping" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "socialLife" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "transportation" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "education1" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "education2" SET DEFAULT ARRAY[]::TEXT[];
